### ISSUE TITLE
better "import"

### ISSUE THREAD

**Issue by ltaulell** [CarineRey/apytram#2]
Proposed changes:

* From my python memento, ```apytram/lib/__init__.py``` should contain the following:

```
from . import Aligner.py
from . import ApytramClasses.py
from . import ApytramNeeds.py
from . import BlastPlus.py
from . import Trinity.py
```

* ```lib/``` directory should be renamed in ```Apytram/```, or ```ApytramLib/```, which then can be imported in ```apytram.py``` as:

```
import Apytram # or ApytramLib
```

* path to ```apytram/<new-lib/-name>``` should be added to ```PYTHONPATH```

A+, Loïs

**Comment by CarineRey** [comment]
Thank you

You can now add  ApytramLib into the``` PYTHONPATH``` if  ```apytram.py``` and ```ApytramLib``` are not in the same directory.

A+, Carine
